# Generated by Django 4.1.3 on 2023-05-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_skil', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
