# Generated by Django 4.1.3 on 2023-05-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_skill_delete_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user_skill',
            new_name='skills',
        ),
    ]
